### ISSUE TITLE
Autosuggestions not making any suggestions

### ISSUE THREAD

**Issue by Locutus64** [jotyGill/ezsh#29]
I just installed CachyOS which is Arch based and right after checking updates I installed python3 and ezsh, closed Konsole and looged out. Once back on the desktop launched Konsole to start doing some installs. I did sudo pacman 
-S yay and installed yay, started typing sudo again and noticed no auto suggestions were being made. Tried several more times and still no auto suggestions. This is the second time right out of the gate that this has happened. I installed Garuda the other day and the same thing. I have never seen this happen with ezsh before so have no idea why it's misbehaving now. Any thoughts and or suggestions would be greatly appreciated. Thanks

**Comment by jotyGill** [comment]
Sorry missed your issue. As the config indicates it's disabled by default now. It conflicts with "marker", if you use that.

`    # zsh-autosuggestions     # disable when using marker, otherwise enable`

You can enable it in your person config file (any name) under ~/.config/ezsh/zshrc/

Add this to the config:
`plugins+=(zsh-autosuggestions)`

There's an example config file shown in the project.

PS: suggestions are still present when when you use arrow up keys
